# Acceptance criteria for the story beside this file.
#
# Documentation first, and not executable: no Gherkin runner is wired to it, so
# nothing here is enforced by existing. What holds the code to it is a test per
# scenario, named for the scenario, in this repository's CI.
#
# One scenario is tagged @manual, and only one: `start` is a Tauri binary whose
# window cannot be opened in CI, so the dialog is confirmed by a person. Every
# other scenario here is a pure function of the project root and the state
# directory, which is why the notice is built as one.

Feature: The launcher announces its retirement
  `start` keeps working for the whole of this major, and says on every run that
  it is deprecated and where to go instead. The documentation says the same.

  Background:
    Given a project built on this template
    And the launcher built from this repository

  Scenario: Every run says it is deprecated
    When the launcher is run
    Then it writes to standard error that it is deprecated
    And it names the version that removes it

  Scenario: A project that has not migrated is told how to
    Given the project has no configuration generated by the extension
    When the launcher is run
    Then the notice names the extension and where to get it

  Scenario: A project that has already migrated is told what to use instead
    Given the project has a configuration generated by the extension
    When the launcher is run
    Then the notice says the project is already configured for the host editor
    And it names the editor command that opens it

  Scenario: Somebody else's configuration is not mistaken for a migration
    # A file with the right name and the wrong contents must not earn
    # "already configured". The generated marker is the test, and a file that
    # cannot be parsed is treated as absent.
    Given the project has a dev container configuration this project did not write
    When the launcher is run
    Then the notice names the extension and where to get it

  Scenario: The notice comes before the container
    When the launcher is run
    Then the notice is written before Docker is contacted

  Scenario: The launcher still launches
    # FR-51. The announcement is not a refusal, and this is the scenario that
    # says so: the whole story must leave the old path working.
    When the launcher is run
    Then the container is brought up and the window opens as before

  Scenario: A state directory that cannot be written does not silence the dialog
    Given the user's state directory cannot be written
    When the launcher is run
    Then the dialog is still shown
    And the notice is still written to standard error

  @manual
  Scenario: The dialog is shown once and then not again
    Given the launcher has never been run on this machine
    When the launcher is run
    Then a dialog says it is deprecated and where to go
    And dismissing it lets the launch continue
    When the launcher is run again
    Then no dialog is shown
    And the notice is still written to standard error

  Scenario: The documentation names the editor as the way in
    When a new reader follows this repository's own instructions
    Then they are told to open the project in the host's editor
    And `start` is presented as deprecated and still working
